### ISSUE TITLE
The VisualizationPanel.updateData method doesn't update survey results when using a custom SurveyAnalytics.HistogramModel visualizer

### ISSUE THREAD

**Issue by JaneGaid** [surveyjs/survey-analytics#271]
I registered a custom visualizer and used `SurveyAnalytics.HistogramModel` to visualize survey results. Unfortunately, the [VisualizationPanel.updateData](https://surveyjs.io/Documentation/Analytics?id=visualizationpanel#updateData) function doesn't update survey results: [Example](https://plnkr.co/edit/sQJDP0RTlVwPXXCX).

The issue was originally reported at [Refresh Survey Result](https://surveyjs.answerdesk.io/ticket/details/t10459/refresh-survey-result).

**Comment by tsv2013** [comment]
In order to be updated dynamically all visualizers inside a panel should have the same data provider.
You need to pass a dataProvider object from passed options to the HistogramVisaualizer constructor.

Here is the updated plunker - https://plnkr.co/edit/OQ67P2t9vvjmWOrF
I'll also update demos on our site,
