### ISSUE TITLE
Tabulator - Server-Side (Remote) Pagination

### ISSUE THREAD

**Issue by JaneSjs** [surveyjs/survey-analytics#329]
T12812 - Display Survey Results in Table - Server-Side Pagination 
https://surveyjs.answerdesk.io/internal/ticket/details/T12812

The SurveyJS Table visualizer is currently using [local pagination](https://github.com/surveyjs/survey-analytics/blob/master/src/tables/tabulator.ts#L136).

Suggestion: support the [server-side/remote pagination](https://tabulator.info/docs/5.4/page#remote) for SurveyJS Table visualizer.

**Comment by tsv2013** [comment]
At this moment we're working on client-side libraries only. We don't have plans to implement back-ends for them (at least right now). Probably in this case user need to use 3rd party grid/table control connected to users back-end.

I'd prefer to close this issue rather then keep it in our back log.

**Comment by JaneSjs** [comment]
A users asks for options to process large data using a SurveyJS Dashboard. I believe that server-side pagination may be an option.

T13312 - Query regarding Fetching Data by API to populate the Dashboard
https://surveyjs.answerdesk.io/internal/ticket/details/T13312

**Comment by AndOne1974** [comment]
+1

**Comment by JaneSjs** [comment]
+1 T17610 - Re: Surveyjs Dashboard - pagination in 'Texts in table' table
https://surveyjs.answerdesk.io/internal/ticket/details/T17610

**Comment by synth** [comment]
This feature seems really important when considering large data sets (10k+ rows). Unless there is guidance on how to performantly send this size of data across the wire, we would love to see more first class support for common mechanisms that deal with large datasets such as server side pagination. 

I think this is a client side feature because the client side table can establish a convention passing standardized parameters like `page`, `per_page`, which can be passed to a function that implements an ajax request to some backend implemented by us developers. 

It's worth noting that large data is also an issue with graphs as the library requires the data being loaded up front. This makes sense to a degree, but is really indicative of a larger problem due to aggregating the results on the client side. This leads to some insecurity as the full raw data will be available on the client. This could be mitigated by the server side, but it's more performant to do the aggregation on the server side, anyhow. 

This is a somewhat separate issue but its generally related to the need to use SurveyJS with large, remote data sets and to do so performantly :)

**Comment by tsv2013** [comment]
We returned back to this issue and decided to implement client side API allowing to support server side paging for tabulator visualizer.

It will be a function passed instead of a data array passed to the Tabulator constructor. This function will accept data fetching parameters like offset, limit (and filteering/sorting settings in the future) and a callback called with selected data and some additional info like total rows count.

Customer will build server request via his custom code, perform it and call our callback with selected data.
You can check the linked commits/PR for more details.

We also plan to prepare an example and update our documentation.
