### ISSUE TITLE
Multi-Select Matrix - Impossible to define the chartType property for the VisualizationMatrixDropdown visualizer type

### ISSUE THREAD

**Issue by JaneSjs** [surveyjs/survey-analytics#449]
T18921 - Why does programmatically setting the chartType not work on matrix question charts?
https://surveyjs.answerdesk.io/internal/ticket/details/T18921
***
https://github.com/surveyjs/survey-analytics/blob/a4b1c6823f39e041fa5215e1d4877292dbb469ad/src/visualizationMatrixDropdown.ts#L13

Impossible to specify the `chartType` option for this visualizer object.

**Comment by tsv2013** [comment]
`VisualizationMatrixDropdown` class is being used for "matrixdropdown" question contains inner object of VisualizationPanel type that is being used for columns visualization (this inner visualizer is exposed via `matrixDropdownVisualizer` property). Columns of such a matrix can be of different types and column questions visualizers can have disjoint sets of chart types, further more, matrix column can't even have the chart type property (e.g. if column contains text). That's why `VisualizationMatrixDropdown` class doesn't have `chartType` property.

**Comment by JaneSjs** [comment]
@tsv2013 the type of a matrix column visualizer can be changed as follows.
```
// Change the type of a matrix column visualizer
vizPanel.visualizers[1]._matrixDropdownVisualizer.visualizers[0].chartType = "pie";
```
Could we consider an API for this?
