### ISSUE TITLE
Visualize Text Entry Questions as Charts - Bars are duplicated when changing a bar type

### ISSUE THREAD

**Issue by JaneSjs** [surveyjs/survey-analytics#488]
T20618 - Chart rendering issue in "Visualize Text Entry Questions as Charts demo"
https://surveyjs.answerdesk.io/internal/ticket/details/T20618
***
To reproduce the issue, run this demo: [Visualize Text Entry Questions as Charts](https://surveyjs.io/dashboard/examples/visualize-answers-from-text-entry-fields-with-charts/reactjs). Change a chart type to Vertical Bar and back to Bar. You can see that bars are duplicated:

https://github.com/user-attachments/assets/bcbb16be-f5d9-45c2-8b4d-9b45fad0dddd

**Comment by lattaai3** [comment]
Hello, I tried to fix the issue

This is what I did:

Updated the CustomVisualizer function to clear the values array before recalculating, preventing duplication of bars when changing chart types.

I also created pull request: https://github.com/surveyjs/survey-analytics/pull/489


> [!CAUTION]
> Disclaimer: This fix was created by Latta AI and you should never merge before you check the correctness of generated code!
>
> The fix provided by Latta AI might not be complete and it can serve as an inspiration.

---
This bug was fixed for free by Latta AI - https://latta.ai/ourmission

If you no longer want Latta AI to attempt fixing issues on your repository, you can block this account.
